### ISSUE TITLE
Going live issue

### ISSUE THREAD

**Issue by jimbrend** [v0l/zap.stream#10]
![image](https://github.com/user-attachments/assets/bdf0e46d-853a-4049-a3e1-53c21637b6e4)

Here this server URL works, on dashboard. 

However, elsewhere it is rtmp://in.zap.stream/live2, and I cannot go live with any other Server URL on any other screen because it is 2, and on the dashboard, it is not.

**Comment by jimbrend** [comment]
I think rtmp://ln.zap.stream/live 

and 

rtmp://ln.zap.stream/live2

are displayed in two different locations, 

Still trying to learn the difference.

**Comment by v0l** [comment]
`live2` = no recording

**Comment by jimbrend** [comment]
ah interesting thank you @v0l 
So I am seeing live 2 I guess in different modals?

Thank you!

**Comment by v0l** [comment]
Yea on the dashboard there is a checkbox for recording on/off, this changes from `live` / `live2`

**Comment by jimbrend** [comment]
ahh got it,
live2 = no recording
live = recording 

and these are saved I think 3 months if recording on, and no way to delete iirc?  didn't want to like dox my address by accident sometimes, 

thank you for explaining!

**Comment by jimbrend** [comment]
> Hi, getting ddosed again

ugh really, ok ill try again later :) ty for making zap stream it's really cool, i will try to multicast to it once back up.

**Comment by jimbrend** [comment]
heya @v0l, @echennells and @markhodl / https://x.com/stopmarkhodl both were also trying to stream just now getting failed to connect error, my stream for some reason shows me still live they let me know but i went offine for a while and computer has been off since then and i can't seem to go live again, just FYI for status rn:

![Image](https://github.com/user-attachments/assets/b16705bf-ffd1-4cf1-8693-1d1935ff1a4b)



![Image](https://github.com/user-attachments/assets/f620cc25-f648-4771-a873-e5ca77ffa460)

**Comment by jimbrend** [comment]
> Yea on the dashboard there is a checkbox for recording on/off, this changes from `live` / `live2`

Was wondering @v0l does this still apply to like: `rtmp://in.ca.zap.stream:1935/good`

appending live2 somewhere here won't generate a VOD?  Thank you for your time :pray:
