### ISSUE TITLE
Video concantenates when a short stream is restarted immediately

### ISSUE THREAD

**Issue by tidley** [v0l/zap.stream#12]
I use OBS with streaming configured.

I started a stream then stopped after a minute or so. I almost immediately started another stream. The second video contains the first video as the intro, then it switches to the second at about a minute's worth of time. A recording of the event:

https://zap.stream/naddr1qqjxgwt9vyuxxc3j94jxgd3e956rsdtx95ukxwps956nwe3ev93rzvnrvy6rqq3qeaz6dwsnvwkha5sn5puwwyxjgy26uusundrm684lg3vw4ma5c2jsxpqqqpmxw7x23gl

The first short recording is overlayed onto the second it seems.

**Comment by v0l** [comment]
Yes it will resume, you need to stop and wait for the stream to go offline on zap.stream first.

This is to allow people to resume the stream if their connection drops or something, its completely intentional
