### ISSUE TITLE
My stream key / going live issue

### ISSUE THREAD

**Issue by jimbrend** [v0l/zap.stream#14]
I'm not sure if it's me in incognito I still am getting this too when clicking Edit Stream Info it was just stuck on refreshing animation

![image](https://github.com/user-attachments/assets/c780f8cc-d8c4-403b-85bc-1ef2ff953277)

Normally here after signing in on my dashboard there right on the left I would see my key and just copy it from there and start streaming

![image](https://github.com/user-attachments/assets/dbc9a3aa-f1d3-447a-89a4-ee7325e1bcd6)

I was going to go live on Zap Stream today but couldn't figure it out after refreshing :/ 

Advise? TYSM

**Comment by v0l** [comment]
You probably need to SYNC the clock on your PC, the AUTH requests use strict timestamp checks

**Comment by jimbrend** [comment]
> You probably need to SYNC the clock on your PC, the AUTH requests use strict timestamp checks

that might've been it i reinstalled windows 11 and had to resync my time I will try again ASAP/tonight

**Comment by jimbrend** [comment]
im live it was one of these toggles iirc after I clean installed Windows 11 it was indeed my time wasn't set
![image](https://github.com/user-attachments/assets/4d971e03-ecd9-43de-8512-14b8e3eab039)


Working now ty.
