### ISSUE TITLE
VOD lifecycle

### ISSUE THREAD

**Issue by ktamas77** [v0l/zap.stream#16]
Excellent service, i just had my first live stream yesterday!

Two quick questions:

1) how long VODs are accessible at the moment? 
2) is there a chance to manually remove or hide vods if needed? This would be a super important feature, to have some control over visibility over time.

**Comment by v0l** [comment]
> how long VODs are accessible at the moment?

VOD's are kept for 90 days atm

> is there a chance to manually remove or hide vods if needed

Not right now, its planned for the new backend which is still in progress (among other things)
